version: "3.11"

services:
  bookshelf:
    container_name: bookshelf
    image: bookshelf
    build:
      dockerfile: Dockerfile
    environment:
      - "DATABASE_URL=/app/db/database.db"
      - "ADDRESS=0.0.0.0:3000"
    volumes:
      - ./db:/app/db
    ports:
      - 3000:3000

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - bookshelf
