version: "3.11"

services:
  bookshelf:
    container_name: bookshelf
    image: bookshelf
    build:
      dockerfile: Dockerfile
    environment:
      - "DATABASE_URL=/app/db/database.db"
      - "ADDRESS=0.0.0.0:3000"
    volumes:
      - ./db:/app/db
    # restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  sqlite-data:
